#
# EFI Boot Guard
#
# Copyright (c) Siemens AG, 2017
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

env:
  matrix:
    - TARGET=native
    - TARGET=i586
    - TARGET=cppcheck
language: c

compiler:
  - gcc

sudo: required

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:444 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

install:
  - sudo apt-get install gcc-multilib gnu-efi libpci-dev libz-dev:i386
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial universe'
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends --target-release xenial libcmocka-dev

addons:
  coverity_scan:
    project:
      name: "siemens/efibootguard"
      description: "Build submitted via Travis CI"
    notification_email: efibootguard-dev@googlegroups.com
    build_command_prepend: "./.travis-build.sh coverity_prepare"
    build_command: "./.travis-build.sh coverity_build"
    branch_pattern: coverity_scan

script:
  - ./.travis-build.sh
