#
# EFI Boot Guard
#
# Copyright (c) Siemens AG, 2017
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

env:
  matrix:
    - TARGET=native
    - TARGET=i586
    - TARGET=cppcheck
language: c

compiler:
  - gcc

sudo: required

before_install:
  - if [ $TRAVIS_BRANCH = coverity_scan ] && [ ${TRAVIS_JOB_NUMBER##*.} != 1 ]; then exit 0; fi
  - echo -n | openssl s_client -connect scan.coverity.com:444 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  coverity_scan:
    project:
      name: "siemens/efibootguard"
      description: "Build submitted via Travis CI"
    notification_email: jan.kiszka@siemens.com
    build_command_prepend: "./.travis-build.sh coverity_prepare"
    build_command: "./.travis-build.sh coverity_build"
    branch_pattern: coverity_scan

cache:
  directories:
  - /opt/cppcheck

script:
  - ./.travis-build.sh
